services:
    # server
    web:
        build:
          dockerfile: ./server/Dockerfile
        volumes:
          # - ./app:/var/www/html
          - ./server/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "80:80"
        
    # application
    app:
      build:
        dockerfile: ./coder/Dockerfile
        # image: garyclarke/php-framework-app
      volumes:
        - ./app:/var/www/html
        - ./coder/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      extra_hosts:
        - host.docker.internal:host-gateway


